conf/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from conf.views import handler404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('resume/', include('resume.urls', namespace='resume')),
    path('certifications/', include('certifications.urls', namespace='certifications')),
    path('projects/', include('projects.urls', namespace='projects')),
    path('contact/', include('contact.urls', namespace='contact')),
]

handler404 = 'conf.views.handler404'

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

contact/urls.py
from django.urls import path
from .views import contact_view

app_name = 'contact'

urlpatterns = [
    path('', contact_view, name='send-message'),
]

home/urls.py
from django.urls import path
from home.views import HomeView, AboutView

app_name = 'home'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
]

resume/urls.py
from django.urls import path
from resume.views import ResumeView

app_name = 'resume'

urlpatterns = [
    path('', ResumeView.as_view(), name='page'),
]

templates/bases/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <title>Index - Personal Bootstrap Template</title>
    <meta name="description" content="">
    <meta name="keywords" content="">

    <!-- Favicons -->
    <link href="{% static 'img/favicon.png' %}" rel="icon">
    <link href="{% static 'img/apple-touch-icon.png' %}" rel="apple-touch-icon">

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com" rel="preconnect">
    <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/aos/aos.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">

    <!-- Main CSS File -->
    <link href="{% static 'css/main.css' %}" rel="stylesheet">

    <!-- =======================================================
    * Template Name: Personal
    * Template URL: https://bootstrapmade.com/personal-free-resume-bootstrap-template/
    * Updated: Nov 04 2024 with Bootstrap v5.3.3
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->
</head>

<body class="{% if request.path == '/' %}index-page
{% elif request.path == '/resume/' %}resume-page
{% elif request.path == '/about/' %}about-page
{% elif request.path == '/contact/' %}contact-page
{% elif request.path == '/portfolio/' %}portfolio-page
{% elif request.path == '/portfolio/details/' %}portfolio-details-page
{% elif request.path == '/service/' %}services-page
{% elif request.path == '/service/details/' %}service-details-page
{% endif %}">

{% include 'bases/header.html' %}

{% block content %}{% endblock %}

{% include 'bases/footer.html' %}


<!-- Scroll Top -->
<a href="#" id="scroll-top" class="scroll-top d-flex align-items-center justify-content-center"><i
        class="bi bi-arrow-up-short"></i></a>

<!-- Preloader -->
<div id="preloader"></div>

<!-- Vendor JS Files -->
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'vendor/php-email-form/validate.js' %}"></script>
<script src="{% static 'vendor/aos/aos.js' %}"></script>
<script src="{% static 'vendor/typed.js/typed.umd.js' %}"></script>
<script src="{% static 'vendor/purecounter/purecounter_vanilla.js' %}"></script>
<script src="{% static 'vendor/waypoints/noframework.waypoints.js' %}"></script>
<script src="{% static 'vendor/swiper/swiper-bundle.min.js' %}"></script>
<script src="{% static 'vendor/glightbox/js/glightbox.min.js' %}"></script>
<script src="{% static 'vendor/imagesloaded/imagesloaded.pkgd.min.js' %}"></script>
<script src="{% static 'vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>

<!-- Main JS File -->
<script src="{% static 'js/main.js' %}"></script>

</body>

</html>

templates/bases/footer.html
{% load static %}
<footer id="footer" class="footer dark-background">
    <div class="container">
        <h3 class="sitename">Personal</h3>
        <p>{{quote}}</p>
        <div class="social-links d-flex justify-content-center">
            {% for media_app in social_media_apps %}
            <a href="{{media_app.social_media_url}}"><i class="bi bi-{{media_app.social_media_app}}"></i></a>
            {% endfor %}
        </div>
<!--        <div class="container">-->
<!--            <div class="copyright">-->
<!--                <span>Copyright</span> <strong class="px-1 sitename">Personal</strong> <span>All Rights Reserved</span>-->
<!--            </div>-->
<!--            <div class="credits">-->
<!--            </div>-->
<!--        </div>-->
    </div>
</footer>

templates/bases/header.html
{% load static %}
  <header id="header" class="header d-flex align-items-center fixed-top">
    <div class="container-fluid container-xl position-relative d-flex align-items-center justify-content-between">

      <a href="{% url 'home:home' %}" class="logo d-flex align-items-center">
        <!-- Uncomment the line below if you also wish to use an image logo -->
        <!-- <img src="assets/img/logo.png" alt=""> -->
        <h1 class="sitename">Personal</h1>
      </a>

      <nav id="navmenu" class="navmenu">
        <ul>
          <li><a href="{% url 'home:home' %}" class="{% if request.path == '/' %}active{% endif %}">Home</a></li>
          <li><a href="{% url 'home:about' %}" class="{% if request.path == '/about/' %}active{% endif %}">About</a></li>
          <li><a href="{% url 'resume:page' %}" class="{% if request.path == '/resume/' %}active{% endif %}">Resume</a></li>
          <li><a href="{% url 'projects:page' %}" class="{% if request.path == '/projects/' %}active{% endif %}">Projects</a></li>
          <li><a href="{% url 'certifications:page' %}" class="{% if request.path == '/certifications/' %}active{% endif %}">Certifications</a></li>
<!--          <li class="dropdown"><a href="#"><span>Dropdown</span> <i class="bi bi-chevron-down toggle-dropdown"></i></a>-->
<!--            <ul>-->
<!--              <li><a href="#">Dropdown 1</a></li>-->
<!--              <li class="dropdown"><a href="#"><span>Deep Dropdown</span> <i class="bi bi-chevron-down toggle-dropdown"></i></a>-->
<!--                <ul>-->
<!--                  <li><a href="#">Deep Dropdown 1</a></li>-->
<!--                  <li><a href="#">Deep Dropdown 2</a></li>-->
<!--                  <li><a href="#">Deep Dropdown 3</a></li>-->
<!--                  <li><a href="#">Deep Dropdown 4</a></li>-->
<!--                  <li><a href="#">Deep Dropdown 5</a></li>-->
<!--                </ul>-->
<!--              </li>-->
<!--              <li><a href="#">Dropdown 2</a></li>-->
<!--              <li><a href="#">Dropdown 3</a></li>-->
<!--              <li><a href="#">Dropdown 4</a></li>-->
<!--            </ul>-->
          </li>
          <li><a href="{% url 'contact:send-message' %}" class="{% if request.path == '/contact/' %}active{% endif %}">Contact</a></li>
        </ul>
        <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
      </nav>

    </div>
  </header>