conf/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from conf.views import handler404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('resume/', include('resume.urls', namespace='resume')),
    path('certifications/', include('certifications.urls', namespace='certifications')),
    path('projects/', include('projects.urls', namespace='projects')),
    path('contact/', include('contact.urls', namespace='contact')),
]

handler404 = 'conf.views.handler404'

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

contact/urls.py
from django.urls import path
from .views import contact_view

app_name = 'contact'

urlpatterns = [
    path('', contact_view, name='send-message'),
]

home/urls.py
from django.urls import path
from home.views import HomeView, AboutView

app_name = 'home'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
]

projects/urls.py
from django.urls import path
from .views import ProjectsView, ProjectDetailsView


app_name = 'projects'

urlpatterns = [
    path('', ProjectsView.as_view(), name='page'),
    path('details/<int:id>/', ProjectDetailsView.as_view(), name='details'),
]

resume/urls.py
from django.urls import path
from resume.views import ResumeView

app_name = 'resume'

urlpatterns = [
    path('', ResumeView.as_view(), name='page'),
]

certifications/models.py
from django.utils import timezone
from django.db import models
from cloudinary.models import CloudinaryField
from django.core.validators import URLValidator


class BioModel(models.Model):
    bio = models.TextField()

    class Meta:
        verbose_name = 'Certifications Bio'
        verbose_name_plural = 'Certifications Bios'



class CategoriesModel(models.Model):
    name = models.CharField(max_length=25)
    to_display = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def joined_name(self):
        return '_'.join(self.name.split(' '))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'



class CertificationsModel(models.Model):
    title = models.CharField(max_length=125)

    image = CloudinaryField('image', null=True, blank=True)  # For photos

    description = models.TextField()
    category = models.ForeignKey(
        CategoriesModel,
        on_delete=models.PROTECT,
        related_name='certifications'
    )
    given_time = models.DateField(default=timezone.now)
    given_by = models.CharField(max_length=100)
    link = models.URLField(null=True, blank=True, validators=[URLValidator(message="Enter a valid URL.")])

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Certification"
        verbose_name_plural = "Certifications"
        ordering = ['-given_time']

    def __str__(self):
        return self.title

contact/models.py
from django.db import models


class ContactInfoModel(models.Model):
    address = models.CharField(max_length=125, null=True, blank=True)
    phone_number = models.CharField(max_length=15, null=True, blank=True)
    email_address = models.EmailField(null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Contact Info'
        verbose_name_plural = 'Contact Infos'

projects/models.py
from django.db import models
from cloudinary.models import CloudinaryField


class BioModel(models.Model):
    bio = models.TextField()

    class Meta:
        verbose_name = 'Project Bio'
        verbose_name_plural = 'Project Bios'

class CategoryModel(models.Model):
    name = models.CharField(max_length=25)
    to_display = models.BooleanField(default=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'


class ProjectModel(models.Model):
    name = models.CharField(max_length=50)
    logo = CloudinaryField('image', blank=True, default='mydxtkgk21jlefrsghkn')
    short_description = models.CharField(max_length=150, null=True, blank=True)
    category = models.ManyToManyField(CategoryModel, related_name='projects')
    full_description = models.TextField(null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Project'
        verbose_name_plural = 'Projects'


class SkillsAppliedModel(models.Model):
    skill = models.CharField(max_length=50)
    project = models.ForeignKey(ProjectModel, on_delete=models.CASCADE, related_name='skills')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.skill

    class Meta:
        verbose_name = 'Skill'
        verbose_name_plural = 'Skills'


class ProjectInformationModel(models.Model):
    title = models.CharField(max_length=25)
    text = models.CharField(max_length=200)
    is_url = models.BooleanField(default=False)
    project = models.ForeignKey(ProjectModel, on_delete=models.CASCADE, related_name='infos')


    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Info'
        verbose_name_plural = 'Infos'


class ProjectImageModel(models.Model):
    image = CloudinaryField('image')
    project = models.ForeignKey(ProjectModel, on_delete=models.CASCADE, related_name='images')

    class Meta:
        verbose_name = 'Image'
        verbose_name_plural = 'Images'

resume/models.py
from django.db import models


class ResumePageModel(models.Model):
    intro = models.TextField(null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.intro[:50]

    class Meta:
        verbose_name = 'Resume Page'
        verbose_name_plural = 'Resume Page'


class EducationsModel(models.Model):
    title = models.CharField(max_length=100)
    from_date = models.DateField()
    to_date = models.DateField()
    present_on = models.BooleanField(null=False)
    institution = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    head = models.ForeignKey(ResumePageModel, on_delete=models.CASCADE, related_name='educations')



    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Education'
        verbose_name_plural = 'Educations'



class ExperiencesModel(models.Model):
    position = models.CharField(max_length=100)
    from_date = models.DateField(null=True, blank=True)
    to_date = models.DateField(null=True, blank=True)
    present_on = models.BooleanField(null=False)
    company = models.CharField(max_length=100)


    text1 = models.TextField(null=True, blank=True)
    text2 = models.TextField(null=True, blank=True)
    text3 = models.TextField(null=True, blank=True)
    text4 = models.TextField(null=True, blank=True)

    head = models.ForeignKey(ResumePageModel, on_delete=models.CASCADE, related_name='experiences')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.position

    class Meta:
        verbose_name = 'Work Experience'
        verbose_name_plural = 'Work Experiences'


class SummaryModel(models.Model):
    section_title = models.CharField(max_length=25) # someone might call it, for example, "overall"; therefore i made this section name dynamic
    name = models.CharField(max_length=50)
    long_description = models.TextField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.section_title

    class Meta:
        verbose_name = 'Resume Page Summary'
        verbose_name_plural = 'Resume Page Summary'


class SummarySmallInfosModel(models.Model):
    short_text = models.CharField(max_length=60)
    head = models.ForeignKey(SummaryModel, on_delete=models.CASCADE, related_name='short_texts')

    def __str__(self):
        return self.short_text

    class Meta:
        verbose_name = 'Text'
        verbose_name_plural = 'Texts'

certifications/views.py
from django.views.generic import TemplateView
from .models import CertificationsModel, CategoriesModel, BioModel
from home.models import SocialMediaModel

class CertificationsView(TemplateView):
    template_name = 'certifications.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        data = CertificationsModel.objects.filter(category__to_display=True)
        context['data'] = data
        context['social_media_apps'] = SocialMediaModel.objects.all()
        context['categories'] = CategoriesModel.objects.all()
        context['bio'] = BioModel.objects.first().bio


        return context


class CertificationDetailsView(TemplateView):
    template_name = 'certification-details.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        certificate_id = self.kwargs.get('id')
        data = CertificationsModel.objects.filter(id=certificate_id).first()
        context['data'] = data
        context['social_media_apps'] = SocialMediaModel.objects.all()
        context['bio'] = BioModel.objects.first().bio

        return context

contact/views.py
import os

from django.shortcuts import render, redirect
from django.contrib import messages
from .models import ContactInfoModel
from home.models import SocialMediaModel
import requests
from django.conf import settings

BOT_TOKEN = os.getenv("BOT_TOKEN")
CHAT_ID = os.getenv("CHAT_ID")

def send_telegram_message(chat_id, message, bot_token):
    url = f"https://api.telegram.org/bot{bot_token}/sendMessage"
    data = {
        "chat_id": chat_id,
        "text": message,
        "parse_mode": "HTML",
    }
    requests.post(url, data=data)


def contact_view(request):
    if request.method == "POST":
        name = request.POST.get("name")
        email = request.POST.get("email")
        subject = request.POST.get("subject")
        message = request.POST.get("message")

        telegram_message = (
            f"<b>New Contact Form Submission</b>\n\n"
            f"<b>👤 Name :</b> {name}\n"
            f"<b>📧 Email :</b> {email}\n"
            f"<b>✍️ Subject :</b> {subject}\n"
            f"<b>📩 Message :</b>\n{message}"
        )

        try:
            send_telegram_message(CHAT_ID, telegram_message, BOT_TOKEN)
            messages.success(request, "Your message has been sent successfully!")
        except Exception as e:
            messages.error(request, f"An error occurred: {e}")
        return redirect("contact:send-message")

    return render(request, "contact.html",
                  {"data": ContactInfoModel.objects.first(), 'social_media_apps': SocialMediaModel.objects.all()})

projects/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from projects.models import ProjectModel, CategoryModel, BioModel
from home.models import SocialMediaModel


class ProjectsView(TemplateView):
    template_name = 'projects.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        data = ProjectModel.objects.filter(category__to_display=True).distinct().order_by('-created_at')
        context['data'] = data
        context['bio'] = BioModel.objects.first().bio
        social_media_apps = SocialMediaModel.objects.all()
        context['social_media_apps'] = social_media_apps
        return context


class ProjectDetailsView(TemplateView):
    template_name = 'project-details.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        project_id = self.kwargs.get('id')
        project = ProjectModel.objects.get(id=project_id)
        context['project'] = project
        context['bio'] = BioModel.objects.first().bio
        context['social_media_apps'] = SocialMediaModel.objects.all()
        context['categories'] = CategoryModel.objects.filter(to_display=True)
        return context

resume/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from resume.models import SummaryModel, ResumePageModel
from home.models import SocialMediaModel


class ResumeView(TemplateView):
    template_name = 'resume.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        resume_data = ResumePageModel.objects.first()
        summary = SummaryModel.objects.all()
        if summary:
            summary = summary.first()

        social_media_apps = SocialMediaModel.objects.all()
        context['social_media_apps'] = social_media_apps
        context['resume_data'] = resume_data
        context['summary'] = summary

        return context

templates/about.html
{% extends 'bases/base.html' %}
{% load static %}
{% block content %}
<main class="main">

    <!-- Page Title -->
    <div class="page-title" data-aos="fade">
        <div class="heading">
            <div class="container">
                <div class="row d-flex justify-content-center text-center">
                    <div class="col-lg-8">
                        <h1>About</h1>
                        <p class="mb-0">{{data.bio}}</p>
                    </div>
                </div>
            </div>
        </div>
        <nav class="breadcrumbs">
            <div class="container">
                <ol>
                    <li><a href="{% url 'home:home' %}">Home</a></li>
                    <li class="current">About</li>
                </ol>
            </div>
        </nav>
    </div><!-- End Page Title -->

    <!-- About Section -->
    <section id="about" class="about section">

        <div class="container" data-aos="fade-up" data-aos-delay="100">

            <div class="row gy-4 justify-content-center">
                <div class="col-lg-4">
                    <img src="{{data.image_on_the_left.url}}" class="img-fluid" alt="">
                </div>
                <div class="col-lg-8 content">
                    <h2>{{data.profession}}</h2>
                    <p class="fst-italic py-3">
                        {{data.text_above_bio}}
                    </p>
                    <div class="row">
                        <div class="col-lg-6">
                            <ul>
                                {% for info in biography_infos_left%}
                                <li><i class="bi bi-chevron-right"></i> <strong>{{info.title}}:</strong>
                                    <span>{{info.text}}</span></li>
                                {% endfor %}
                            </ul>
                        </div>
                        <div class="col-lg-6">
                            <ul>
                                {% for info in biography_infos_right%}
                                <li><i class="bi bi-chevron-right"></i> <strong>{{info.title}}:</strong> <span>{{info.text}}</span>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                    <p class="py-3">
                        {{data.text_below_bio}}
                    </p>
                </div>
            </div>

        </div>

    </section><!-- /About Section -->

    <!-- Stats Section -->
    {% if data.number_for_smile and data.text_for_smile  or data.text_for_headphones and data.number_for_headphones or data.text_for_people and data.number_for_people or data.text_for_notebook and data.number_for_notebook%}
    <section id="stats" class="stats section">

        <div class="container" data-aos="fade-up" data-aos-delay="100">

            <div class="row gy-4">
                {% if data.text_for_smile and data.number_for_smile %}
                <div class="col-lg-3 col-md-6 d-flex flex-column align-items-center">
                    <i class="bi bi-emoji-smile"></i>
                    <div class="stats-item">
                        <span data-purecounter-start="0" data-purecounter-end="{{data.number_for_smile}}"
                              data-purecounter-duration="1"
                              class="purecounter"></span>
                        <p>{{data.text_for_smile}}</p>
                    </div>
                </div><!-- End Stats Item -->
                {% endif %}


                {% if data.text_for_notebook and data.number_for_notebook%}
                <div class="col-lg-3 col-md-6 d-flex flex-column align-items-center">
                    <i class="bi bi-journal-richtext"></i>
                    <div class="stats-item">
                        <span data-purecounter-start="0" data-purecounter-end="{{data.number_for_notebook}}"
                              data-purecounter-duration="1"
                              class="purecounter"></span>
                        <p>{{data.text_for_notebook}}</p>
                    </div>
                </div><!-- End Stats Item -->
                {% endif %}


                {% if data.text_for_people and data.number_for_people%}
                <div class="col-lg-3 col-md-6 d-flex flex-column align-items-center">
                    <i class="bi bi-headset"></i>
                    <div class="stats-item">
                        <span data-purecounter-start="0" data-purecounter-end="{{data.number_for_headphones}}"
                              data-purecounter-duration="1"
                              class="purecounter"></span>
                        <p>{{data.text_for_headphones}}</p>
                    </div>
                </div><!-- End Stats Item -->
                {% endif %}


                {% if data.text_for_people and data.number_for_people%}
                <div class="col-lg-3 col-md-6 d-flex flex-column align-items-center">
                    <i class="bi bi-people"></i>
                    <div class="stats-item">
                        <span data-purecounter-start="0" data-purecounter-end="{{data.number_for_people}}"
                              data-purecounter-duration="1"
                              class="purecounter"></span>
                        <p>{{data.text_for_people}}</p>
                    </div>
                </div><!-- End Stats Item -->
                {% endif %}
            </div>

        </div>

    </section><!-- /Stats Section -->
    {% endif %}

    <!-- Skills Section -->
    {% if skills_left %}
    <section id="skills" class="skills section">

        <!-- Section Title -->
        <div class="container section-title" data-aos="fade-up">
            <h2>Skills</h2>
            <div><span>My</span> <span class="description-title">Skills</span></div>
        </div><!-- End Section Title -->

        <div class="container" data-aos="fade-up" data-aos-delay="100">

            <div class="row skills-content skills-animation">

                <div class="col-lg-6">
                    {% for skill in skills_left %}
                    <div class="progress">
                        <span class="skill"><span>{{skill.skill}}</span> <i class="val">{{skill.personal_number_skill}}{% if skill.is_percent%}%{% endif %}</i></span>
                        <div class="progress-bar-wrap">
                            <div class="progress-bar" role="progressbar" aria-valuenow="{{skill.personal_number_skill}}"
                                 aria-valuemin="0"
                                 aria-valuemax="{{skill.max_number_skill}}"></div>
                        </div>
                    </div><!-- End Skills Item -->
                    {% endfor %}

                </div>

                <div class="col-lg-6">
                    {% for skill in skills_right %}
                    <div class="progress">
                        <span class="skill"><span>{{skill.skill}}</span> <i class="val">{{skill.personal_number_skill}}{% if skill.is_percent%}%{% endif %}</i></span>
                        <div class="progress-bar-wrap">
                            <div class="progress-bar" role="progressbar" aria-valuenow="{{skill.personal_number_skill}}"
                                 aria-valuemin="0"
                                 aria-valuemax="{{skill.max_number_skill}}"></div>
                        </div>
                    </div><!-- End Skills Item -->
                    {% endfor %}
                </div>

            </div>

        </div>

    </section><!-- /Skills Section -->
    {% endif %}

    {% if data.interests.all %}
    <!-- Interests Section -->
    <section id="interests" class="interests section">

        <!-- Section Title -->
        <div class="container section-title" data-aos="fade-up">
            <h2>Features</h2>
            <div><span>I'm</span> <span class="description-title">interested in</span></div>
        </div><!-- End Section Title -->

        <div class="container">

            <div class="row gy-4">
                {% for interest in data.interests.all %}
                <div class="col-lg-3 col-md-4" data-aos="fade-up" data-aos-delay="{{forloop.counter}}00">
                    <div class="features-item">
                        <i class="bi bi-star" style="color: #ffbb2c;"></i>
                        <h3><a href="" class="stretched-link">{{interest.name}}</a></h3>
                    </div>
                </div><!-- End Feature Item -->
                {% endfor %}
            </div>

        </div>

    </section><!-- /Interests Section -->
    {% endif %}

    {% if  data.testimonials.all%}
    <!-- Testimonials Section -->
    <section id="testimonials" class="testimonials section">

        <!-- Section Title -->
        <div class="container section-title" data-aos="fade-up">
            <h2>Testimonials</h2>
            <div><span>Check my</span> <span class="description-title">Testimonials</span></div>
        </div><!-- End Section Title -->

        <div class="container" data-aos="fade-up" data-aos-delay="100">

            <div class="swiper init-swiper" data-speed="600" data-delay="5000">
                <script type="application/json" class="swiper-config">
                    {
                        "loop": true,
                        "speed": 600,
                        "autoplay": {
                            "delay": 5000
                        },
                        "slidesPerView": "auto",
                        "pagination": {
                            "el": ".swiper-pagination",
                            "type": "bullets",
                            "clickable": true
                        },
                        "breakpoints": {
                            "320": {
                                "slidesPerView": 1,
                                "spaceBetween": 40
                            },
                            "1200": {
                                "slidesPerView": 3,
                                "spaceBetween": 20
                            }
                        }
                    }
                </script>
                <div class="swiper-wrapper">
                    {% for testimonial in data.testimonials.all %}
                    <div class="swiper-slide">
                        <div class="testimonial-item">
                            <p>
                                <i class="bi bi-quote quote-icon-left"></i>
                                <span>{{testimonial.text}}</span>
                                <i class="bi bi-quote quote-icon-right"></i>
                            </p>
                            <img src="{{testimonial.image.url}}" class="testimonial-img"
                                 alt="">
                            <h3>{{testimonial.name}}</h3>
                            <h4>{{testimonial.profession_or_relation}}</h4>
                        </div>
                    </div><!-- End testimonial item -->
                    {% endfor %}

                </div>
                <div class="swiper-pagination"></div>
            </div>

        </div>

    </section><!-- /Testimonials Section -->
    {% endif %}

</main>
{% endblock %}

templates/certifications.html
{% extends 'bases/base.html' %}
{% load static %}
{% block content %}
<main class="main">

    <!-- Page Title -->
    <div class="page-title" data-aos="fade">
        <div class="heading">
            <div class="container">
                <div class="row d-flex justify-content-center text-center">
                    <div class="col-lg-8">
                        <h1>Certifications</h1>
                        <p class="mb-0">{{bio}}</p>
                    </div>
                </div>
            </div>
        </div>
        <nav class="breadcrumbs">
            <div class="container">
                <ol>
                    <li><a href="{% url 'home:home' %}">Home</a></li>
                    <li class="current">Certifications</li>
                </ol>
            </div>
        </nav>
    </div><!-- End Page Title -->

    <!-- Certifications Section -->
    <section id="portfolio" class="portfolio section">

        <div class="container">

            <div class="isotope-layout" data-default-filter="*" data-layout="masonry" data-sort="original-order">

                <ul class="portfolio-filters isotope-filters" data-aos="fade-up" data-aos-delay="100">
                    <li data-filter="*" class="filter-active">All</li>
                    {% for category in categories %}
                    <li data-filter=".filter-{{category.joined_name}}">{{category.name}}</li>
                    {% endfor %}
                </ul><!-- End Certifications Filters -->

                <div class="row gy-4 isotope-container" data-aos="fade-up" data-aos-delay="200">
                    {% for certification in data %}

                    <div class="col-lg-4 col-md-6 portfolio-item isotope-item filter-{{certification.category.joined_name}}">
                        <div class="portfolio-content h-100">
                            <img src="{{certification.image.url}}" class="img-fluid" alt="">
                            <div class="portfolio-info">
                                <h4>{{certification.category.name}}</h4>
                                <p>{{certification.category.title}}</p>
                                <a href="{{certification.image.url}}" title="{{certification.category.title}}"
                                   data-gallery="portfolio-gallery-app" class="glightbox preview-link"><i
                                        class="bi bi-zoom-in"></i></a>
                                <a href="{% url 'certifications:details' certification.id %}" title="More Details"
                                   class="details-link"><i class="bi bi-link-45deg"></i></a>
                            </div>
                        </div>
                    </div><!-- End Portfolio Item -->
                    {% endfor %}


                </div><!-- End Certifications Container -->

            </div>

        </div>

    </section><!-- /Certifications Section -->

</main>
{% endblock %}

templates/index.html
{% extends 'bases/base.html' %}
{% load static %}
{% block content %}
<main class="main">

    <!-- Hero Section -->
    <section id="hero" class="hero section dark-background">

        <img src="{{image.url}}" alt="" data-aos="fade-in">

        <div class="container" data-aos="zoom-out" data-aos-delay="100">
            <h2>{{name}}</h2>
            <p>I'm <span class="typed"
                         data-typed-items="{% if titles %}{% for title in titles %}{{ title }}{% if not forloop.last %},{% endif %}{% endfor %}{% else %}No one{% endif %}">{{first_title}}</span><span
                    class="typed-cursor typed-cursor--blink"></span></p>
            <div class="social-links">
                {% for media_app in social_media_apps %}
                <a href="{{media_app.social_media_url}}"><i class="bi bi-{{media_app.social_media_app}}"></i></a>
                {% endfor %}
            </div>
        </div>

    </section><!-- /Hero Section -->

</main>
{% endblock %}

templates/projects.html
{% extends 'bases/base.html' %}
{% load static %}
{% block content %}
<main class="main">

    <!-- Page Title -->
    <div class="page-title" data-aos="fade">
        <div class="heading">
            <div class="container">
                <div class="row d-flex justify-content-center text-center">
                    <div class="col-lg-8">
                        <h1>Projects</h1>
                        <p class="mb-0">{{bio}}</p>
                    </div>
                </div>
            </div>
        </div>
        <nav class="breadcrumbs">
            <div class="container">
                <ol>
                    <li><a href="{% url 'home:home' %}">Home</a></li>
                    <li class="current">Projects</li>
                </ol>
            </div>
        </nav>
    </div><!-- End Page Title -->

    <!-- Projects Section -->
    <section id="services" class="services section">

        <div class="container">

            <div class="row gy-4">
                {% for project in data%}
                <div class="col-lg-4 col-md-6" data-aos="fade-up" data-aos-delay="{{forloop.counter}}00">
                    <div class="service-item  position-relative">
                        <div class="icon">
                            <!--                <i class="bi bi-activity"></i>-->
                            <img src="{{ project.logo.url }}" alt="Project Logo" class="img-fluid"
                                 style="width: 60px; height: 60px; object-fit: contain;">

                        </div>
                        <a href="{% url 'projects:details' project.id %}" class="stretched-link">
                            <h3>{{project.name}}</h3>
                        </a>
                        {% if project.short_description %}
                        <p style="color: #1a1a1a;">{{project.short_description}}</p>
                        {% endif %}
                    </div>
                </div><!-- End Service Item -->
                {% endfor %}

            </div>

        </div>

    </section><!-- /Projects Section -->

</main>
{% endblock %}